#!/bin/bash

mountpoint="$(pwd)/.private"
vault="$(pwd)/.private_enc"

is_mounted=$(mount | grep -c "$mountpoint ")
if [[ $is_mounted -gt 0 ]]; then
	printf '"%s" is already mounted.\n' "$mountpoint"
	exit 0
fi
printf 'Mounting vault here: "%s"...\n' "$mountpoint"
echo "$pass" | encfs -S "$vault" "$mountpoint"
