#!/bin/bash

tmpdir="/dev/shm/listicl.es_generators"
generators="$(pwd)/generators"
mountpoint="$(pwd)/generators_tmpfs"

if ! [[ -d $tmpdir ]]; then
	printf 'Creating tmpdir "%s".' "$tmpdir"
	mkdir "$tmpdir"
	ln -s "$tmpdir" "$mountpoint"
fi

printf 'Copying generators to tmpfs...\n'
cp -r "$generators"/* "$mountpoint/"
